version: 2.1

docker_defaults: &docker_defaults
  docker:
    - image: circleci/node:10
  working_directory: ~/repo

restore_cache: &restore_cache
  restore_cache:
    keys:
      - v1-dependencies-{{ checksum "package.json" }}
      # fallback to using the latest cache if no exact match is found
      - v1-dependencies-

install_steps: &install_steps
  - checkout
  - *restore_cache
  - run: yarn install

jobs:
  install:
    <<: *docker_defaults
    <<: *install_steps
  build:
    <<: *docker_defaults
    steps:
      - run: yarn build --production
  pushcdn:
    <<: *docker_defaults
    steps:
      - run: yarn pushcdn
  deploy:
    <<: *docker_defaults
    steps:
      - run: yarn deploy


workflows:
  version: 2
  install-and-build:
    jobs:
      - install
      - build
          requires:
            - install
      - pushcdn
          requires:
            - build
      - deploy
          requires:
            - pushcdn


